title: Earth Songs
description: Hymns and Marches for the great turning
sitename: Earth Songs
baseurl: '/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
